-- Optional seed of current page copy (string values only; image imports skipped).
insert into public.page_content (key, page, label, value, type) values
  (E'home.header.brandPrefix', E'home', E'Header logo prefix', E'Alpha', E'text'),
  (E'home.header.brandAccent', E'home', E'Header logo accent', E'Digi', E'text'),
  (E'home.header.brandSuffix', E'home', E'Header logo suffix', E'AI', E'text'),
  (E'home.header.logoAlt', E'home', E'Header logo alt text', E'ADAi Chartered Accountants', E'text'),
  (E'home.nav.home', E'home', E'Nav: Home', E'Home', E'text'),
  (E'home.nav.about', E'home', E'Nav: About Us', E'About Us', E'text'),
  (E'home.nav.services', E'home', E'Nav: Services', E'Services', E'text'),
  (E'home.nav.blog', E'home', E'Nav: Blog', E'Blog', E'text'),
  (E'home.nav.knowledge', E'home', E'Nav: Knowledge', E'Knowledge', E'text'),
  (E'home.nav.careers', E'home', E'Nav: Careers', E'Careers', E'text'),
  (E'home.nav.contact', E'home', E'Nav: Contact', E'Contact', E'text'),
  (E'home.header.contactCta', E'home', E'Header contact button', E'Contact', E'text'),
  (E'home.hero.eyebrow', E'home', E'Hero eyebrow', E'Alpha Digi AI Accountants LTD, CHARTERED ACCOUNTANTS, London', E'text'),
  (E'home.hero.headingBrand', E'home', E'Hero heading (highlighted)', E'Chartered Accountants', E'text'),
  (E'home.hero.ctaPrimary', E'home', E'Hero primary button', E'See Our Services', E'text'),
  (E'home.hero.ctaSecondary', E'home', E'Hero secondary button', E'Contact Us', E'text'),
  (E'home.hero.videoUrl', E'home', E'Hero video URL', E'/hero-video.mp4', E'text'),
  (E'home.about.eyebrow', E'home', E'About section eyebrow', E'We are Alpha Digi AI', E'text'),
  (E'home.about.headingBrand', E'home', E'About heading (highlighted)', E'ICAEW member', E'text'),
  (E'home.about.headingSuffix', E'home', E'About heading suffix', E'.', E'text'),
  (E'home.about.ctaPrimary', E'home', E'About primary button', E'More about us', E'text'),
  (E'home.about.ctaSecondary', E'home', E'About secondary button', E'Make an appointment', E'text'),
  (E'home.about.yearsValue', E'home', E'About years badge number', E'12', E'text'),
  (E'home.about.yearsLabel', E'home', E'About years badge label', E'Years of expertise', E'text'),
  (E'home.services.eyebrow', E'home', E'Services section eyebrow', E'Our Services', E'text'),
  (E'home.services.headingPrefix', E'home', E'Services heading prefix', E'Everything you need to run ', E'text'),
  (E'home.services.headingBrand', E'home', E'Services heading (highlighted)', E'smarter finances', E'text'),
  (E'home.services.headingSuffix', E'home', E'Services heading suffix', E'.', E'text'),
  (E'home.services.cta', E'home', E'Services view-all button', E'View all services', E'text'),
  (E'home.why.eyebrow', E'home', E'Why-choose eyebrow', E'What Makes Us Different?', E'text'),
  (E'home.why.headingPrefix', E'home', E'Why-choose heading prefix', E'Expertise you can trust, ', E'text'),
  (E'home.why.headingBrand', E'home', E'Why-choose heading (highlighted)', E'technology', E'text'),
  (E'home.why.headingSuffix', E'home', E'Why-choose heading suffix', E' you''ll love.', E'text'),
  (E'home.why.feature1.title', E'home', E'Why-choose feature 1 title', E'Bringing The Numbers To Life', E'text'),
  (E'home.why.feature2.title', E'home', E'Why-choose feature 2 title', E'Expertise', E'text'),
  (E'home.why.feature3.title', E'home', E'Why-choose feature 3 title', E'Personable Service', E'text'),
  (E'home.why.cta', E'home', E'Why-choose primary button', E'Speak to our team today', E'text'),
  (E'home.why.callPrefix', E'home', E'Why-choose call-us prefix', E'Call us now on', E'text'),
  (E'home.testimonials.eyebrow', E'home', E'Testimonials section eyebrow', E'Testimonials', E'text'),
  (E'home.testimonials.headingPrefix', E'home', E'Testimonials heading prefix', E'What our ', E'text'),
  (E'home.testimonials.headingBrand', E'home', E'Testimonials heading (highlighted)', E'clients say', E'text'),
  (E'home.testimonials.headingSuffix', E'home', E'Testimonials heading suffix', E'.', E'text'),
  (E'home.testimonials.cta', E'home', E'Testimonials CTA button', E'Get a free consultation', E'text'),
  (E'home.cta.heading', E'home', E'Contact CTA heading', E'Any questions? Speak to our team today.', E'text'),
  (E'home.cta.contactButton', E'home', E'Contact CTA button', E'Contact Us', E'text'),
  (E'home.footer.headingBrand', E'home', E'Footer heading (highlighted)', E'grow', E'text'),
  (E'home.footer.headingSuffix', E'home', E'Footer heading suffix', E'?', E'text'),
  (E'home.footer.cta', E'home', E'Footer CTA button', E'Contact Us', E'text'),
  (E'home.footer.icaewImageAlt', E'home', E'Footer ICAEW logo alt text', E'ICAEW Chartered Accountant', E'text'),
  (E'home.footer.icaewHref', E'home', E'Footer ICAEW logo link', E'https://www.icaew.com', E'text'),
  (E'home.seo.ogTitle', E'home', E'Home Open Graph title', E'Alpha Digi AI — Chartered Accountants in London', E'text'),
  (E'home.seo.image', E'home', E'Default social share image', E'/favicon.jpeg', E'text'),
  (E'home.seo.imageAlt', E'home', E'Default social share image alt', E'ADAi Chartered Accountants logo', E'text'),
  (E'about.seo.title', E'about', E'About SEO title', E'About Us | Alpha Digi AI Accountants', E'text'),
  (E'about.seo.ogTitle', E'about', E'About Open Graph title', E'About Alpha Digi AI Accountants', E'text'),
  (E'about.eyebrow', E'about', E'About page eyebrow', E'About Us', E'text'),
  (E'about.headingPrefix', E'about', E'About page heading prefix', E'Modern accountancy, ', E'text'),
  (E'about.headingBrand', E'about', E'About page heading (highlighted)', E'human at heart.', E'text'),
  (E'about.tagline', E'about', E'About page tagline', E'Chartered accountants for over 12 years.', E'text'),
  (E'about.badge.1', E'about', E'About badge 1', E'ICAEW registered Firm', E'text'),
  (E'about.badge.2', E'about', E'About badge 2', E'HMRC registered agent', E'text'),
  (E'about.badge.3', E'about', E'About badge 3', E'AI driven solution', E'text'),
  (E'about.badge.4', E'about', E'About badge 4', E'Payroll and HMRC support', E'text'),
  (E'about.badge.5', E'about', E'About badge 5', E'Service with Care', E'text'),
  (E'about.badge.6', E'about', E'About badge 6', E'VAT and HMRC support', E'text'),
  (E'about.numbers.heading', E'about', E'Numbers section heading', E'Bringing The Numbers To Life', E'text'),
  (E'about.numbers.expertise.title', E'about', E'Expertise block title', E'Expertise', E'text'),
  (E'about.numbers.personable.title', E'about', E'Personable block title', E'Personable Service', E'text'),
  (E'about.different.eyebrow', E'about', E'Differences section eyebrow', E'What Makes Us Different?', E'text'),
  (E'about.different.1.title', E'about', E'Difference 1 title', E'Bringing The Numbers To Life', E'text'),
  (E'about.different.2.title', E'about', E'Difference 2 title', E'Expertise', E'text'),
  (E'about.different.3.title', E'about', E'Difference 3 title', E'Personable Service', E'text'),
  (E'about.testimonials.eyebrow', E'about', E'About testimonials eyebrow', E'Testimonials', E'text'),
  (E'about.testimonials.heading', E'about', E'About testimonials heading', E'What our clients say.', E'text'),
  (E'services.seo.title', E'services', E'Services SEO title', E'Accounting & Compliance Services | Alpha Digi', E'text'),
  (E'services.seo.ogTitle', E'services', E'Services Open Graph title', E'Accounting & Compliance Services', E'text'),
  (E'services.eyebrow', E'services', E'Services page eyebrow', E'Our Services', E'text'),
  (E'services.headingPrefix', E'services', E'Services page heading line 1', E'Digital-First Cloud', E'text'),
  (E'services.ctaPrimary', E'services', E'Services page primary button', E'Get in Touch', E'text'),
  (E'services.ctaSecondary', E'services', E'Services page secondary button', E'Explore 10 Core Services', E'text'),
  (E'services.list.cta', E'services', E'Services list button', E'View all services', E'text'),
  (E'services.highlight.2', E'services', E'Services highlight 2', E'Payroll & Payments', E'text'),
  (E'services.highlight.4', E'services', E'Services highlight 4', E'VAT Return Filing', E'text'),
  (E'services.highlight.6', E'services', E'Services highlight 6', E'Non-Statutory Audit', E'text'),
  (E'services.highlight.7', E'services', E'Services highlight 7', E'Management Accounts', E'text'),
  (E'services.core.eyebrow', E'services', E'Core services eyebrow', E'Our Services', E'text'),
  (E'services.core.headingPrefix', E'services', E'Core services heading prefix', E'10 Core ', E'text'),
  (E'services.core.headingBrand', E'services', E'Core services heading (highlighted)', E'Services', E'text'),
  (E'services.card.cta', E'services', E'Service card button', E'Learn More', E'text'),
  (E'services.partners.eyebrow', E'services', E'Partners eyebrow', E'Integrations', E'text'),
  (E'blog.seo.title', E'blog', E'Blog SEO title', E'Blog | Alpha Digi AI Accountants', E'text'),
  (E'blog.seo.ogTitle', E'blog', E'Blog Open Graph title', E'Blog | Alpha Digi AI Accountants', E'text'),
  (E'blog.eyebrow', E'blog', E'Blog page eyebrow', E'Blog', E'text'),
  (E'blog.headingPrefix', E'blog', E'Blog heading prefix', E'Insights, guides and ', E'text'),
  (E'blog.headingBrand', E'blog', E'Blog heading (highlighted)', E'updates', E'text'),
  (E'blog.headingSuffix', E'blog', E'Blog heading suffix', E'.', E'text'),
  (E'blog.card.cta', E'blog', E'Blog card button', E'Read more', E'text'),
  (E'careers.seo.title', E'careers', E'Careers SEO title', E'Careers at Alpha Digi AI Accountants', E'text'),
  (E'careers.seo.ogTitle', E'careers', E'Careers Open Graph title', E'Join Our Team | Alpha Digi Careers', E'text'),
  (E'careers.eyebrow', E'careers', E'Careers page eyebrow', E'Join Our Team', E'text'),
  (E'careers.headingPrefix', E'careers', E'Careers heading prefix', E'Careers at ', E'text'),
  (E'careers.headingBrand', E'careers', E'Careers heading (highlighted)', E'Alpha Digi', E'text'),
  (E'careers.culture.eyebrow', E'careers', E'Culture section eyebrow', E'Our Culture', E'text'),
  (E'careers.culture.heading', E'careers', E'Culture section heading', E'Life at Alpha Digi AI Accountants', E'text'),
  (E'careers.culture.1.title', E'careers', E'Culture card 1 title', E'Flexible Working', E'text'),
  (E'careers.culture.2.title', E'careers', E'Culture card 2 title', E'Modern Tools', E'text'),
  (E'careers.culture.3.title', E'careers', E'Culture card 3 title', E'Growth Path', E'text'),
  (E'careers.culture.4.title', E'careers', E'Culture card 4 title', E'Inclusive Value', E'text'),
  (E'careers.values.heading', E'careers', E'Values heading', E'Our Values', E'text'),
  (E'careers.values.1', E'careers', E'Value 1', E'Trust & Confidentiality at the core.', E'text'),
  (E'careers.values.2', E'careers', E'Value 2', E'AI-assisted efficiency, human-centric advisory.', E'text'),
  (E'careers.values.3', E'careers', E'Value 3', E'Commitment to continuous training and compliance.', E'text'),
  (E'careers.values.4', E'careers', E'Value 4', E'Responsive, direct client communication.', E'text'),
  (E'careers.digital.heading', E'careers', E'Digital WE heading', E'Digital “WE” Philosophy', E'text'),
  (E'careers.pathways.eyebrow', E'careers', E'Career pathways eyebrow', E'Career Pathways', E'text'),
  (E'careers.pathways.heading', E'careers', E'Career pathways heading', E'Find Your Place in Our Firm', E'text'),
  (E'careers.role.idealLabel', E'careers', E'Role “ideal for” label', E'Ideal for:', E'text'),
  (E'careers.role.cta', E'careers', E'Role apply button', E'Apply', E'text'),
  (E'contact.seo.title', E'contact', E'Contact SEO title', E'Contact Alpha Digi AI Accountants', E'text'),
  (E'contact.seo.ogTitle', E'contact', E'Contact Open Graph title', E'Contact Alpha Digi AI Accountants', E'text'),
  (E'contact.eyebrow', E'contact', E'Contact page eyebrow', E'Contact', E'text'),
  (E'contact.headingPrefix', E'contact', E'Contact heading prefix', E'Speak to our ', E'text'),
  (E'contact.headingBrand', E'contact', E'Contact heading (highlighted)', E'team today.', E'text'),
  (E'contact.detail.phoneLabel', E'contact', E'Contact phone label', E'Phone', E'text'),
  (E'contact.detail.emailLabel', E'contact', E'Contact email label', E'Email', E'text'),
  (E'contact.detail.officeLabel', E'contact', E'Contact office label', E'Office', E'text'),
  (E'contact.detail.hoursLabel', E'contact', E'Contact hours label', E'Hours', E'text'),
  (E'contact.form.heading', E'contact', E'Contact form heading', E'Send us a message', E'text'),
  (E'contact.form.nameLabel', E'contact', E'Contact form name label', E'Name', E'text'),
  (E'contact.form.emailLabel', E'contact', E'Contact form email label', E'Email', E'text'),
  (E'contact.form.phoneLabel', E'contact', E'Contact form phone label', E'Phone', E'text'),
  (E'contact.form.messageLabel', E'contact', E'Contact form message label', E'How can we help?', E'text'),
  (E'contact.form.submit', E'contact', E'Contact form submit button', E'Send message', E'text'),
  (E'knowledge.seo.title', E'knowledge', E'Knowledge SEO title', E'Knowledge | Alpha Digi AI Accountants', E'text'),
  (E'knowledge.seo.ogTitle', E'knowledge', E'Knowledge Open Graph title', E'Knowledge | Alpha Digi AI Accountants', E'text'),
  (E'knowledge.eyebrow', E'knowledge', E'Knowledge page eyebrow', E'Knowledge', E'text'),
  (E'knowledge.headingPrefix', E'knowledge', E'Knowledge heading prefix', E'Guides, checklists and ', E'text'),
  (E'knowledge.headingBrand', E'knowledge', E'Knowledge heading (highlighted)', E'resources', E'text'),
  (E'knowledge.headingSuffix', E'knowledge', E'Knowledge heading suffix', E'.', E'text'),
  (E'knowledge.card.cta', E'knowledge', E'Knowledge download button', E'Download PDF', E'text')
on conflict (key) do nothing;

insert into public.page_content (key, page, label, value, type) values
  ('home.header.logoUrl', 'home', 'Header logo image', '/cms/adai-logo.jpeg', 'text'),
  ('home.hero.imageDesktop', 'home', 'Hero image (desktop)', '/cms/accountant.webp', 'text'),
  ('home.hero.imageMobile', 'home', 'Hero image (mobile)', '/cms/accountant-mobile.webp', 'text'),
  ('home.about.imageUrl', 'home', 'About section image', '/cms/acc-bridge.jpg', 'text'),
  ('home.footer.icaewImageUrl', 'home', 'Footer ICAEW image', '/cms/finalicaewlogo.jpeg', 'text')
on conflict (key) do nothing;
