-- Run this in the Supabase SQL Editor (do not run from the app).
-- H3 storage hardening:
-- 1. knowledge-files is private (no anonymous public URL access).
-- 2. Neither bucket is listable by anon (no SELECT policy on storage.objects).
-- card-images stays a public bucket so known image URLs still work without listing.
--
-- After this script, published Knowledge downloads use short-lived signed URLs
-- generated by the app (src/lib/knowledge-signed-url.ts).

update storage.buckets
set public = true
where id = 'card-images';

update storage.buckets
set public = false
where id = 'knowledge-files';

drop policy if exists storage_public_select on storage.objects;
